### ISSUE TITLE
Game Center Leaderboards screen displays with a transparent background on iOS 8.1

### ISSUE THREAD

**Issue by NomiJ** [Wizcorp/phonegap-plugin-gameCenter#13]
Hi, 

I recently got my app rejected due to this reason. On previous iOS SDK version there is no such issue. 

![screenshot_1](https://cloud.githubusercontent.com/assets/8808212/5535083/d0fc83c6-8a95-11e4-9530-bbe37887410a.png)

**Comment by NomiJ** [comment]
Thanks, it seems to be problem with one of other plugin.

**Comment by NomiJ** [comment]
Thanks, it seems to be problem with one of other plugin.

**Comment by aogilvie** [comment]
@NomiJ Out of interest, can you let us know which plugin?

**Comment by NomiJ** [comment]
I was using following wrapper over GameCenter and GooglePlay 
https://github.com/01org/cordova-google-play-games-services/blob/master/readme.md

It uses your plugin for GameCenter Integration. I removed it and just using yours.

**Comment by aogilvie** [comment]
Interesting. Thanks!
