### ISSUE TITLE
Not working in PhoneGap Build

### ISSUE THREAD

**Issue by joshuamorony** [Wizcorp/phonegap-plugin-gameCenter#18]
Hi,

When including this plugin through PhoneGap Build I get the following error (before triggering any plugin related code):

TypeError: undefined is not a function (evaluating 'callback.success.apply(null, args)')

Then when I try to call gameCenter.authenticate nothing happens. If I try to show a leaderboard I get a notification saying 'Game Center Unavailable - Player not signed in'

Any idea what could be causing this?

**Comment by joshuamorony** [comment]
It was a conflicting plugin, haven't worked out which yet but it's all sorted!

**Comment by ronkorving** [comment]
Great, thanks for the confirmation.

**Comment by canado** [comment]
Can you tell which one ?
